# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a8150a9fafd236417f0b49bd38cb5eecbcd2eee03417bf87a20c6d48d5def3ecb28a6a88842584ff9e9c8e2653cd8ed065998b29dadd4f82d4020faf14ba894

test:
  secret_key_base: f319c7543e02d925ba603d3b0fd336eb89d73c5891efb329dc2562286aed355ccef4fa94579e3a666149b1adb4766a3277cdac5358b293dcc9f63b3616a75e85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
