# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c6b12acda511aa797ca3ddc3d21d500c42928a4402a65419e2fbd5935b4e93e16214d488d8b82e0fb9c718fe2b64e146b7a761c490c3db2dbd63f9f66dd5733

test:
  secret_key_base: 45b738d90bf2de31a9405b5a851f61804e8b6d7b4f3b1cbbf82c0758953ddcc06c0450f2929a7845458ab4ee37d7b6ece4c5c4d56070582d0c88808b49375989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
